apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: task02
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-reader
subjects:
- kind: Group
  name: system:serviceaccounts:prometheus
  apiGroup: rbac.authorization.k8s.io
