apiVersion: v1 # Версия API
kind: Pod # Объект, который создаем
metadata:
  name: web
spec:
  containers: # Описание контейнеров внутри Pod
  - name: geckoweb # Название контейнера
    image: maratdasaev/otus # Образ из которого создается контейнер
    volumeMounts:
    - name: app
      mountPath: /app
  initContainers:
    - name: init-myservice
      image: busybox:1.31
      command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
      volumeMounts:
      - name: app
        mountPath: /app
  volumes:
  - name: app
    emptyDir: {}
